"""initial_schema_and_indexes

Revision ID: 3814bac30aec
Revises: 
Create Date: 2026-09-18 22:24:21.757692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3814bac30aec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_abha_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_table('users')
    op.create_index('ix_intake_doctor_status', 'intake_sessions', ['doctor_id', 'status'], unique=False)
    op.create_index('ix_intake_patient_created', 'intake_sessions', ['patient_id', 'created_at'], unique=False)
    op.create_index('ix_intake_session_date', 'intake_sessions', ['session_date'], unique=False)
    op.create_index('ix_doc_file_type', 'patient_documents', ['file_type'], unique=False)
    op.create_index('ix_doc_patient_created', 'patient_documents', ['patient_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doc_patient_created', table_name='patient_documents')
    op.drop_index('ix_doc_file_type', table_name='patient_documents')
    op.drop_index('ix_intake_session_date', table_name='intake_sessions')
    op.drop_index('ix_intake_patient_created', table_name='intake_sessions')
    op.drop_index('ix_intake_doctor_status', table_name='intake_sessions')
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('abha_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('age_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('doctor_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('patient_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_index(op.f('ix_users_abha_id'), 'users', ['abha_id'], unique=True)
    # ### end Alembic commands ###
